site_name: Aaram Se Sounga
# site_url: https://-willett.github.io/mkdocs-material-youtube-tutorial/
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotatate
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.share
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-on-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/sleep
  plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
        lang: [en]

extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shouryade
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/shouryade
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shouryade/

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: shouryade
      repo: dev-docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home:
      - index.md
      - about.md

  - FastAPI:
      - ML Models in FastAPI: FastAPI/ml-models.md

  - OS Fixes (Arch Linux):
      - System Info: os_fixes/index.md
      - HDMI Fix: os_fixes/hdmi_fix.md

  # - Projects: projects.md
copyright: |
  &copy; 2023 <a href="https://github.com/shouryade"  target="_blank" rel="noopener">Shourya De</a>
